name: 'Setup bpkg environment'
description: 'Setup bpkg in environment making available in PATH'
author: 'Joseph Werle <joseph.werle@gmail.com>'

inputs:
  bpkg-version:
    description: 'Version (tag) to use for bpkg'
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo Will fetch bpkg@${{ inputs.bpkg-version }}
        curl -sLo- get.bpkg.sh/${{ inputs.bpkg-version }} | bash
