name: versions

on:
  - pull_request
  - push

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - name: Verify latest
        run: |
          bpkg --version

  v1-0-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpkg-version: 1.0.0
      - name: Verify bpkg@1.0.0
        run: |
          bpkg --version | grep '1.0.0'

  v1-1-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpkg-version: 1.1.0
      - name: Verify bpkg@1.1.0
        run: |
          bpkg --version | grep '1.1.0'

  v1-1-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpkg-version: 1.1.1
      - name: Verify bpkg@1.1.1
        run: |
          bpkg --version | grep '1.1.1'

  v1-1-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpkg-version: 1.1.2
      - name: Verify bpkg@1.1.2
        run: |
          bpkg --version | grep '1.1.2'
